### ISSUE TITLE
if query result more than 999 line attachment is 0 kb file

### ISSUE THREAD

**Issue by goodpress** [StudiOwens/email-mysql-csv#1] opened 2014-12-22 02:41 UTC
if query result more than 999 line attachment is 0 kb file

**Comment by StudiOwens** [comment] 2016-11-22 17:08
Could not reproduce problem. Created a 1,000 line attachment, and a 10,000 line attachment as expected. Closing issue.

**Closed as completed by StudiOwens** 2016-11-22 17:08 UTC
